# Generated by Django 4.1.3 on 2022-12-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("std", models.CharField(max_length=250)),
                ("address", models.CharField(max_length=500)),
                ("phone", models.IntegerField()),
            ],
        ),
    ]
